# Generated by Django 5.2.5 on 2026-05-11 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentattempt',
            name='difficulty_score',
            field=models.FloatField(default=0.5, help_text='Avg difficulty weight of questions answered in this attempt'),
        ),
        migrations.AddField(
            model_name='assessmentattempt',
            name='integrity_factor',
            field=models.FloatField(default=1.0, help_text='Proctoring integrity multiplier applied to this attempt (0.7–1.0)'),
        ),
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', help_text='Difficulty tier used to weight DifficultyScore in VSPS', max_length=10),
        ),
    ]
