import itertools

from django.contrib.auth import get_user_model
from django.core.management.base import BaseCommand, CommandError
from django.utils.text import slugify

from core.models import ApplicantProfile, Internship, RecruiterProfile

User = get_user_model()

INTERNSHIP_DATA = [
    {
        "title": "Software Development Intern",
        "company": "Google",
        "location": "Bangalore",
        "type": "On-site",
        "stipend": 60000,
        "skills": ["Python", "Data Structures", "Algorithms", "System Design"],
        "company_website": "https://careers.google.com",
        "company_linkedin": "https://www.linkedin.com/company/google/",
        "company_size": "10000+ employees",
        "industry": "Technology",
        "company_location": "Bangalore, India",
        "designation": "Campus Recruiter",
        "company_description": "Google is a global technology leader building products that help people connect, search, and collaborate.",
        "phone_number": "+91-80-1234-5678",
    },
    {
        "title": "Frontend Developer Intern",
        "company": "Amazon",
        "location": "Hyderabad",
        "type": "On-site",
        "stipend": 50000,
        "skills": ["React", "JavaScript", "HTML", "CSS"],
        "company_website": "https://www.amazon.jobs",
        "company_linkedin": "https://www.linkedin.com/company/amazon/",
        "company_size": "10000+ employees",
        "industry": "E-commerce",
        "company_location": "Hyderabad, India",
        "designation": "Talent Acquisition Lead",
        "company_description": "Amazon is a global e-commerce and cloud computing leader delivering customer-centric products and services.",
        "phone_number": "+91-40-2345-6789",
    },
    {
        "title": "Machine Learning Intern",
        "company": "Microsoft",
        "location": "Bangalore",
        "type": "Hybrid",
        "stipend": 65000,
        "skills": ["Python", "Machine Learning", "TensorFlow", "Data Science"],
        "company_website": "https://careers.microsoft.com",
        "company_linkedin": "https://www.linkedin.com/company/microsoft/",
        "company_size": "10000+ employees",
        "industry": "Software",
        "company_location": "Bangalore, India",
        "designation": "University Recruiting Manager",
        "company_description": "Microsoft builds productivity and platform solutions used by millions around the world.",
        "phone_number": "+91-80-3456-7890",
    },
    {
        "title": "Backend Developer Intern",
        "company": "Flipkart",
        "location": "Bangalore",
        "type": "On-site",
        "stipend": 45000,
        "skills": ["Java", "Spring Boot", "Microservices", "MySQL"],
        "company_website": "https://www.flipkartcareers.com",
        "company_linkedin": "https://www.linkedin.com/company/flipkart/",
        "company_size": "10000+ employees",
        "industry": "E-commerce",
        "company_location": "Bangalore, India",
        "designation": "Campus Recruitment Partner",
        "company_description": "Flipkart is one of India’s largest e-commerce companies, delivering innovative online shopping experiences.",
        "phone_number": "+91-80-4567-8901",
    },
    {
        "title": "Data Science Intern",
        "company": "Swiggy",
        "location": "Remote",
        "type": "Remote",
        "stipend": 40000,
        "skills": ["Python", "Pandas", "Machine Learning", "SQL"],
        "company_website": "https://careers.swiggy.com",
        "company_linkedin": "https://www.linkedin.com/company/swiggy/",
        "company_size": "5000-10000 employees",
        "industry": "Food Delivery",
        "company_location": "Bangalore, India",
        "designation": "Recruitment Specialist",
        "company_description": "Swiggy connects customers with restaurants and delivery partners through real-time logistics technology.",
        "phone_number": "+91-80-5678-9012",
    },
    {
        "title": "Full Stack Developer Intern",
        "company": "Zomato",
        "location": "Gurgaon",
        "type": "Hybrid",
        "stipend": 42000,
        "skills": ["React", "Node.js", "MongoDB", "Express"],
        "company_website": "https://careers.zomato.com",
        "company_linkedin": "https://www.linkedin.com/company/zomato/",
        "company_size": "5000-10000 employees",
        "industry": "Food Tech",
        "company_location": "Gurgaon, India",
        "designation": "Talent Acquisition Manager",
        "company_description": "Zomato is a food tech company that builds consumer apps and logistics networks for food delivery.",
        "phone_number": "+91-124-678-9012",
    },
    {
        "title": "Cloud Engineering Intern",
        "company": "AWS",
        "location": "Bangalore",
        "type": "On-site",
        "stipend": 70000,
        "skills": ["AWS", "Docker", "Kubernetes", "Linux"],
        "company_website": "https://aws.amazon.com/careers/",
        "company_linkedin": "https://www.linkedin.com/company/amazon-web-services/",
        "company_size": "10000+ employees",
        "industry": "Cloud Computing",
        "company_location": "Bangalore, India",
        "designation": "University Recruiting Lead",
        "company_description": "AWS is a leader in cloud infrastructure, providing scalable computing and data services.",
        "phone_number": "+91-80-6789-0123",
    },
    {
        "title": "DevOps Intern",
        "company": "Infosys",
        "location": "Pune",
        "type": "On-site",
        "stipend": 30000,
        "skills": ["Docker", "CI/CD", "Linux", "Terraform"],
        "company_website": "https://www.infosys.com/careers/",
        "company_linkedin": "https://www.linkedin.com/company/infosys/",
        "company_size": "10000+ employees",
        "industry": "Consulting",
        "company_location": "Pune, India",
        "designation": "Campus Hiring Coordinator",
        "company_description": "Infosys is a global consulting and IT services enterprise supporting digital transformation.",
        "phone_number": "+91-20-7890-1234",
    },
    {
        "title": "AI Research Intern",
        "company": "OpenAI Labs",
        "location": "Remote",
        "type": "Remote",
        "stipend": 80000,
        "skills": ["Python", "Deep Learning", "PyTorch", "NLP"],
        "company_website": "https://openai.com/careers",
        "company_linkedin": "https://www.linkedin.com/company/openai/",
        "company_size": "1000-5000 employees",
        "industry": "Artificial Intelligence",
        "company_location": "Remote - San Francisco, CA",
        "designation": "Research Recruiting Partner",
        "company_description": "OpenAI builds advanced AI research models and applications focused on safe and beneficial outcomes.",
        "phone_number": "+1-415-123-4567",
    },
    {
        "title": "Product Management Intern",
        "company": "Paytm",
        "location": "Noida",
        "type": "Hybrid",
        "stipend": 35000,
        "skills": ["Product Strategy", "Analytics", "Market Research", "Excel"],
        "company_website": "https://paytm.com/careers",
        "company_linkedin": "https://www.linkedin.com/company/paytm/",
        "company_size": "5000-10000 employees",
        "industry": "Fintech",
        "company_location": "Noida, India",
        "designation": "HR Business Partner",
        "company_description": "Paytm provides digital payments and financial services across India.",
        "phone_number": "+91-120-890-1234",
    },
    {
        "title": "Data Analyst Intern",
        "company": "Deloitte",
        "location": "Hyderabad",
        "type": "Hybrid",
        "stipend": 38000,
        "skills": ["SQL", "Python", "Power BI", "Data Visualization"],
        "company_website": "https://www2.deloitte.com/global/en/careers.html",
        "company_linkedin": "https://www.linkedin.com/company/deloitte/",
        "company_size": "10000+ employees",
        "industry": "Professional Services",
        "company_location": "Hyderabad, India",
        "designation": "Campus Recruitment Lead",
        "company_description": "Deloitte provides audit, consulting, tax, and advisory services worldwide.",
        "phone_number": "+91-40-9012-3456",
    },
    {
        "title": "Cybersecurity Intern",
        "company": "Cisco",
        "location": "Bangalore",
        "type": "On-site",
        "stipend": 45000,
        "skills": ["Network Security", "Ethical Hacking", "Linux", "Python"],
        "company_website": "https://www.cisco.com/c/en/us/about/careers.html",
        "company_linkedin": "https://www.linkedin.com/company/cisco/",
        "company_size": "10000+ employees",
        "industry": "Networking",
        "company_location": "Bangalore, India",
        "designation": "Technical Recruiting Lead",
        "company_description": "Cisco is a global leader in networking and cybersecurity technologies.",
        "phone_number": "+91-80-9012-3456",
    },
    {
        "title": "Software Engineering Intern",
        "company": "Adobe",
        "location": "Noida",
        "type": "Hybrid",
        "stipend": 55000,
        "skills": ["Java", "Algorithms", "Spring Boot", "APIs"],
        "company_website": "https://www.adobe.com/careers.html",
        "company_linkedin": "https://www.linkedin.com/company/adobe/",
        "company_size": "10000+ employees",
        "industry": "Software",
        "company_location": "Noida, India",
        "designation": "Recruitment Operations Manager",
        "company_description": "Adobe creates digital experiences and creative software for individuals and businesses.",
        "phone_number": "+91-120-3456-7890",
    },
    {
        "title": "Mobile App Developer Intern",
        "company": "PhonePe",
        "location": "Bangalore",
        "type": "On-site",
        "stipend": 42000,
        "skills": ["Flutter", "Dart", "Firebase", "REST APIs"],
        "company_website": "https://www.phonepe.com/careers/",
        "company_linkedin": "https://www.linkedin.com/company/phonepe/",
        "company_size": "5000-10000 employees",
        "industry": "Fintech",
        "company_location": "Bangalore, India",
        "designation": "Talent Acquisition Partner",
        "company_description": "PhonePe offers digital payments and financial services for consumers and merchants.",
        "phone_number": "+91-80-3456-1234",
    },
    {
        "title": "Business Analyst Intern",
        "company": "McKinsey",
        "location": "Mumbai",
        "type": "On-site",
        "stipend": 50000,
        "skills": ["Excel", "Data Analysis", "Business Intelligence", "SQL"],
        "company_website": "https://www.mckinsey.com/careers",
        "company_linkedin": "https://www.linkedin.com/company/mckinsey-and-company/",
        "company_size": "10000+ employees",
        "industry": "Consulting",
        "company_location": "Mumbai, India",
        "designation": "Campus Recruiting Manager",
        "company_description": "McKinsey helps organizations solve complex business problems and drive growth.",
        "phone_number": "+91-22-1234-5678",
    },
    {
        "title": "UI/UX Design Intern",
        "company": "PayPal",
        "location": "Chennai",
        "type": "Hybrid",
        "stipend": 35000,
        "skills": ["Figma", "UX Research", "Wireframing", "Prototyping"],
        "company_website": "https://www.paypal.com/us/webapps/mpp/jobs",
        "company_linkedin": "https://www.linkedin.com/company/paypal/",
        "company_size": "10000+ employees",
        "industry": "Payments",
        "company_location": "Chennai, India",
        "designation": "Design Recruiting Lead",
        "company_description": "PayPal enables secure online money transfers and digital payment solutions.",
        "phone_number": "+91-44-7890-1234",
    },
    {
        "title": "Blockchain Developer Intern",
        "company": "Polygon",
        "location": "Remote",
        "type": "Remote",
        "stipend": 45000,
        "skills": ["Solidity", "Blockchain", "Web3", "Smart Contracts"],
        "company_website": "https://polygon.technology/careers",
        "company_linkedin": "https://www.linkedin.com/company/polygon-technology/",
        "company_size": "500-1000 employees",
        "industry": "Blockchain",
        "company_location": "Remote - Global",
        "designation": "Recruiter",
        "company_description": "Polygon is a protocol and framework for building and connecting Ethereum-compatible blockchain networks.",
        "phone_number": "+1-415-987-6543",
    },
    {
        "title": "Game Developer Intern",
        "company": "Ubisoft",
        "location": "Pune",
        "type": "On-site",
        "stipend": 32000,
        "skills": ["Unity", "C#", "Game Physics", "3D Graphics"],
        "company_website": "https://www.ubisoft.com/en-us/company/careers",
        "company_linkedin": "https://www.linkedin.com/company/ubisoft/",
        "company_size": "10000+ employees",
        "industry": "Gaming",
        "company_location": "Pune, India",
        "designation": "Talent Acquisition Specialist",
        "company_description": "Ubisoft develops, publishes, and distributes video games for players around the world.",
        "phone_number": "+91-20-1234-7890",
    },
    {
        "title": "Data Engineering Intern",
        "company": "Uber",
        "location": "Hyderabad",
        "type": "Hybrid",
        "stipend": 60000,
        "skills": ["Python", "Spark", "Hadoop", "SQL"],
        "company_website": "https://www.uber.com/global/en/careers/",
        "company_linkedin": "https://www.linkedin.com/company/uber/",
        "company_size": "10000+ employees",
        "industry": "Mobility",
        "company_location": "Hyderabad, India",
        "designation": "Recruitment Lead",
        "company_description": "Uber operates a global mobility platform connecting riders, drivers, and delivery partners.",
        "phone_number": "+91-40-1234-6789",
    },
    {
        "title": "AI Engineer Intern",
        "company": "Nvidia",
        "location": "Bangalore",
        "type": "On-site",
        "stipend": 75000,
        "skills": ["Deep Learning", "CUDA", "Python", "Computer Vision"],
        "company_website": "https://www.nvidia.com/en-us/about-nvidia/careers/",
        "company_linkedin": "https://www.linkedin.com/company/nvidia/",
        "company_size": "10000+ employees",
        "industry": "Semiconductors",
        "company_location": "Bangalore, India",
        "designation": "Technical Recruitment Lead",
        "company_description": "Nvidia creates graphics processing hardware and AI computing platforms.",
        "phone_number": "+91-80-2345-6789",
    },
    {
        "title": "Marketing Intern",
        "company": "Unilever",
        "location": "Mumbai",
        "type": "On-site",
        "stipend": 25000,
        "skills": ["SEO", "Content Marketing", "Analytics", "Social Media"],
        "company_website": "https://www.unilever.com/careers/",
        "company_linkedin": "https://www.linkedin.com/company/unilever/",
        "company_size": "10000+ employees",
        "industry": "Consumer Goods",
        "company_location": "Mumbai, India",
        "designation": "Campus Outreach Manager",
        "company_description": "Unilever manufactures consumer products in food, beauty, and home care categories.",
        "phone_number": "+91-22-6789-0123",
    },
    {
        "title": "Digital Marketing Intern",
        "company": "Byju's",
        "location": "Remote",
        "type": "Remote",
        "stipend": 20000,
        "skills": ["SEO", "Google Analytics", "Content Strategy", "Social Media"],
        "company_website": "https://byjus.com/careers",
        "company_linkedin": "https://www.linkedin.com/company/byjus/",
        "company_size": "5000-10000 employees",
        "industry": "Edtech",
        "company_location": "Remote - Bangalore, India",
        "designation": "Recruiting Partner",
        "company_description": "Byju’s offers online learning programs and education technology solutions.",
        "phone_number": "+91-80-6789-1234",
    },
    {
        "title": "AI Product Intern",
        "company": "Notion AI",
        "location": "Remote",
        "type": "Remote",
        "stipend": 70000,
        "skills": ["AI", "Product Design", "User Research", "Data Analysis"],
        "company_website": "https://www.notion.so/careers",
        "company_linkedin": "https://www.linkedin.com/company/notionhq/",
        "company_size": "1000-5000 employees",
        "industry": "Productivity Software",
        "company_location": "Remote - San Francisco, CA",
        "designation": "Recruitment Lead",
        "company_description": "Notion AI builds collaboration and productivity software for teams and individuals.",
        "phone_number": "+1-415-234-5678",
    },
    {
        "title": "Research Intern",
        "company": "IBM Research",
        "location": "Bangalore",
        "type": "On-site",
        "stipend": 60000,
        "skills": ["Machine Learning", "Python", "Data Science", "Statistics"],
        "company_website": "https://www.ibm.com/careers/us-en/",
        "company_linkedin": "https://www.linkedin.com/company/ibm/",
        "company_size": "10000+ employees",
        "industry": "Research",
        "company_location": "Bangalore, India",
        "designation": "Research Talent Recruiter",
        "company_description": "IBM Research develops advanced computing technologies and AI solutions.",
        "phone_number": "+91-80-7890-1234",
    },
    {
        "title": "Frontend Engineer Intern",
        "company": "Razorpay",
        "location": "Bangalore",
        "type": "Hybrid",
        "stipend": 45000,
        "skills": ["React", "TypeScript", "Tailwind", "JavaScript"],
        "company_website": "https://razorpay.com/careers/",
        "company_linkedin": "https://www.linkedin.com/company/razorpay/",
        "company_size": "1000-5000 employees",
        "industry": "Fintech",
        "company_location": "Bangalore, India",
        "designation": "Recruitment Manager",
        "company_description": "Razorpay offers payments and banking solutions for businesses and developers.",
        "phone_number": "+91-80-8901-2345",
    },
    {
        "title": "Systems Engineer Intern",
        "company": "Intel",
        "location": "Bangalore",
        "type": "On-site",
        "stipend": 55000,
        "skills": ["C++", "Operating Systems", "Computer Architecture", "Linux"],
        "company_website": "https://www.intel.com/content/www/us/en/jobs/jobs-at-intel.html",
        "company_linkedin": "https://www.linkedin.com/company/intel-corporation/",
        "company_size": "10000+ employees",
        "industry": "Semiconductors",
        "company_location": "Bangalore, India",
        "designation": "Global Campus Recruiter",
        "company_description": "Intel designs and manufactures semiconductor chips powering computing devices globally.",
        "phone_number": "+91-80-9012-4567",
    },
    {
        "title": "AI NLP Intern",
        "company": "HuggingFace",
        "location": "Remote",
        "type": "Remote",
        "stipend": 75000,
        "skills": ["Python", "NLP", "Transformers", "Deep Learning"],
        "company_website": "https://huggingface.co/careers",
        "company_linkedin": "https://www.linkedin.com/company/hugging-face/",
        "company_size": "1000-5000 employees",
        "industry": "Artificial Intelligence",
        "company_location": "Remote - Global",
        "designation": "Talent Acquisition Specialist",
        "company_description": "Hugging Face develops open-source tools and models for machine learning and natural language processing.",
        "phone_number": "+1-650-123-4567",
    },
    {
        "title": "FinTech Intern",
        "company": "Stripe",
        "location": "Remote",
        "type": "Remote",
        "stipend": 70000,
        "skills": ["Finance", "APIs", "Python", "Data Analysis"],
        "company_website": "https://stripe.com/jobs",
        "company_linkedin": "https://www.linkedin.com/company/stripe/",
        "company_size": "5000-10000 employees",
        "industry": "Fintech",
        "company_location": "Remote - San Francisco, CA",
        "designation": "Recruitment Partner",
        "company_description": "Stripe provides online payment infrastructure for internet businesses.",
        "phone_number": "+1-415-987-6540",
    },
    {
        "title": "Startup Software Intern",
        "company": "CRED",
        "location": "Bangalore",
        "type": "Hybrid",
        "stipend": 45000,
        "skills": ["React", "Node.js", "MongoDB", "JavaScript"],
        "company_website": "https://cred.club/careers",
        "company_linkedin": "https://www.linkedin.com/company/cred-club/",
        "company_size": "1000-5000 employees",
        "industry": "Fintech",
        "company_location": "Bangalore, India",
        "designation": "Campus Hiring Lead",
        "company_description": "CRED builds financial products and rewards for creditworthy customers.",
        "phone_number": "+91-80-2345-6780",
    },
    {
        "title": "Analytics Intern",
        "company": "KPMG",
        "location": "Delhi",
        "type": "On-site",
        "stipend": 35000,
        "skills": ["SQL", "Power BI", "Excel", "Data Analysis"],
        "company_website": "https://home.kpmg/xx/en/home/careers.html",
        "company_linkedin": "https://www.linkedin.com/company/kpmg/",
        "company_size": "10000+ employees",
        "industry": "Professional Services",
        "company_location": "Delhi, India",
        "designation": "Campus Recruitment Manager",
        "company_description": "KPMG provides audit, tax, and advisory services to organizations worldwide.",
        "phone_number": "+91-11-1234-5678",
    },
]

DEFAULT_PASSWORD = "InternRecruiter123!"


class Command(BaseCommand):
    help = "Seeds recruiter users and internship listings."

    def add_arguments(self, parser):
        parser.add_argument("--password", default=DEFAULT_PASSWORD, help="Password to assign to recruiter accounts.")
        parser.add_argument(
            "--truncate",
            action="store_true",
            help="Delete existing seeded recruiters/internships before seeding.",
        )

    def handle(self, *args, **options):
        password = options["password"]
        if not password or len(password) < 6:
            raise CommandError("Please supply --password with at least 6 characters.")

        recruiter_emails = [self._build_email(entry["company"]) for entry in INTERNSHIP_DATA]

        if options["truncate"]:
            Internship.objects.filter(recruiter__user__email__in=recruiter_emails).delete()
            RecruiterProfile.objects.filter(user__email__in=recruiter_emails).delete()
            User.objects.filter(email__in=recruiter_emails).delete()
            self.stdout.write(self.style.WARNING("Cleared previously seeded recruiter accounts and internships."))

        created_recruiters = 0
        created_internships = 0

        for record in INTERNSHIP_DATA:
            email = self._build_email(record["company"])
            user_defaults = {
                "first_name": record["company"],
                "last_name": "Recruiter",
                "username": self._derive_username(email),
                "role": User.Role.RECRUITER,
            }
            user, created = User.objects.get_or_create(email=email, defaults=user_defaults)
            if created:
                user.set_password(password)
                user.save()
                created_recruiters += 1
            elif user.role != User.Role.RECRUITER:
                user.role = User.Role.RECRUITER
                user.save(update_fields=["role"])

            recruiter_profile, _ = RecruiterProfile.objects.get_or_create(
                user=user,
                defaults={
                    "company_name": record["company"],
                    "company_website": record.get("company_website", ""),
                    "company_linkedin": record.get("company_linkedin", ""),
                    "company_size": record.get("company_size", ""),
                    "industry": record.get("industry", ""),
                    "company_location": record.get("company_location", ""),
                    "designation": record.get("designation", "Recruiter"),
                    "company_description": record.get("company_description", ""),
                    "phone_number": record.get("phone_number", ""),
                },
            )
            recruiter_updates = []
            for field in [
                "company_name",
                "company_website",
                "company_linkedin",
                "company_size",
                "industry",
                "company_location",
                "designation",
                "company_description",
                "phone_number",
            ]:
                if getattr(recruiter_profile, field, None) != record.get(field, ""):
                    setattr(recruiter_profile, field, record.get(field, ""))
                    recruiter_updates.append(field)
            if recruiter_updates:
                recruiter_profile.save(update_fields=recruiter_updates)

            internship, created_listing = Internship.objects.update_or_create(
                recruiter=recruiter_profile,
                title=record["title"],
                defaults={
                    "description": f"{record['company']} {record['title']} opportunity through InternConnect.",
                    "location": record["location"],
                    "required_skills": record["skills"],
                    "work_type": record["type"],
                    "stipend": record["stipend"],
                },
            )
            if created_listing:
                created_internships += 1

        self.stdout.write(
            self.style.SUCCESS(
                f"Seeded/updated {len(INTERNSHIP_DATA)} internships ({created_internships} new) with {created_recruiters} recruiter accounts."
            )
        )

    def _build_email(self, company):
        slug = slugify(company) or "recruiter"
        return f"{slug}@partners.internconnect.ai"

    def _derive_username(self, base_email):
        base = base_email.split("@")[0]
        for idx in itertools.count():
            candidate = base if idx == 0 else f"{base}{idx}"
            if not User.objects.filter(username=candidate).exists():
                return candidate
