# Generated by Django 6.0.3 on 2026-03-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantprofile',
            name='graduation_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='major',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
