# Generated by Django 6.0.3 on 2026-03-15 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_applicantprofile_graduation_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='stipend',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internship',
            name='work_type',
            field=models.CharField(default='On-site', max_length=50),
        ),
    ]
