# Generated by Django 6.0.3 on 2026-03-15 20:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_internship_stipend_internship_work_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enforce_2fa_for_admins_recruiters', models.BooleanField(default=True)),
                ('auto_approve_verified_recruiters', models.BooleanField(default=False)),
                ('recruiter_rating', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('recency_score', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
            ],
            options={
                'verbose_name': 'Platform Setting',
                'verbose_name_plural': 'Platform Settings',
            },
        ),
        migrations.RemoveField(
            model_name='internship',
            name='recency_score',
        ),
        migrations.RemoveField(
            model_name='internship',
            name='recruiter_rating',
        ),
    ]
