# Generated by Django 6.0.3 on 2026-03-15 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_platformsettings_remove_internship_recency_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantprofile',
            name='interested_role',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
