# Generated by Django 5.2.5 on 2026-05-11 20:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_internship_deadline_internship_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantprofile',
            name='assessment_consistency',
            field=models.FloatField(default=0.5, help_text='Stability of accuracy across the last 3 assessment attempts', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='assessment_difficulty_score',
            field=models.FloatField(default=0.5, help_text='Avg difficulty weight of questions answered (easy=0.5, medium=0.75, hard=1.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='integrity_factor',
            field=models.FloatField(default=1.0, help_text='Anti-cheating confidence: 1.0=clean, 0.7=multiple violations', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='internship',
            name='recency_score',
            field=models.FloatField(default=1.0, help_text='Freshness of this internship listing (1=very recent)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='internship',
            name='recruiter_rating',
            field=models.FloatField(default=0.7, help_text='Platform-assigned recruiter quality score (0–1)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
