# Generated by Django 6.0.5 on 2026-05-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_application_source_internshipinvitation_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipinvitation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20),
        ),
    ]
