# Generated by Django 6.0.5 on 2026-05-13 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_internshipinvitation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_invitation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.internshipinvitation'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('invitation', 'Invitation'), ('message', 'Message'), ('application', 'Application'), ('system', 'System')], default='system', max_length=50),
        ),
    ]
